contextdata:
    Door Lock Program:
        Lock: true
        Pressure: toolow
    Drum Motor Program:
        Loudness: normal
        Rotation_Speed: toohigh
        Vibration: normal
    Fan Program:
        Loudness: toohigh
        Mass_Air_Flow: normal
        Vibration: normal
    Pump Out Program:
        Exit_Water_Flow: true
        Water_Level: normal
    Water Inlet Program:
        Entrance_Water_Flow: true
        Water_Hardness: normal
        Water_Level: normal
    Long Time Check:
        Laundry_Fill_Level: normal
        Laundry_Weight: normal
        Washing_Powder_Fill_Level: normal
        Water_Hardness: hard
        Temperature: high
        Usage_Frequency: normal
        Used_Modes: normal
        Washing_Powder: normal